namespace StreetNameRegistry.Municipality
{
    using System;

    // Generated by ChatGPT
    public class LevenshteinDistanceCalculator
    {
        public static int Calculate(string source, string destination)
        {
            int[,] dp = new int[source.Length + 1, destination.Length + 1];

            for (int i = 0; i <= source.Length; i++)
            {
                for (int j = 0; j <= destination.Length; j++)
                {
                    if (i == 0)
                    {
                        dp[i, j] = j;
                    }
                    else if (j == 0)
                    {
                        dp[i, j] = i;
                    }
                    else
                    {
                        int cost = source[i - 1] == destination[j - 1] ? 0 : 1;
                        dp[i, j] = Math.Min(Math.Min(dp[i - 1, j] + 1, dp[i, j - 1] + 1), dp[i - 1, j - 1] + cost);
                    }
                }
            }

            return dp[source.Length, destination.Length];
        }

        public static double CalculatePercentage(string str1, string str2)
        {
            int distance = Calculate(str1, str2);
            int maxLength = Math.Max(str1.Length, str2.Length);

            double percentageDifference = (double)distance / maxLength * 100.0;
            return percentageDifference;
        }
    }
}
