name: Testje

on:
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'Informatievlaanderen'
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: slack-send
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # Slack channel ID where message will be posted. Needed if using bot token
        channel-id: C0323QUJSLE
        # Message to post into Slack. Needed if using bot token
        slack-message: Testje was completed
      env:
        SLACK_BOT_TOKEN: xoxe.xoxp-1-Mi0yLTQ1OTUwNzQ1NTQzLTI2MjMyODg4NTE2NTItNDI1MjgzMTY1MTU3My00MjQ5MTc0NTI4NzkwLWViNjY2YWE1NzBkYWUzMmZlNjZjODk3OTBiYzk3YThlODc5OTJiOWM3NWQ4MzQ3YTdhYTYxMWZmMzc2NGEzM2E
