name: Testje

on:
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'Informatievlaanderen'
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: slack-send
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # Slack channel ID where message will be posted. Needed if using bot token
        channel-id: team-dinosaur-dev
        # Message to post into Slack. Needed if using bot token
        slack-message: Testje was completed
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
